### ISSUE TITLE
HTML formatting of upper box and text "Total Fees Burned" in USD Tab 

### ISSUE THREAD

**Issue by nowhnl** [mohamedmansour/eth-burn#14]
Not sure if there is a scaling issue for this part of the page. Definitely want to see the full USD burned once it continues to grow even larger. 
![Screen Shot 2021-06-24 at 11 49 19 AM](https://user-images.githubusercontent.com/82062327/123337054-64933b00-d4e2-11eb-93fb-036195a806e4.png)

**Comment by mohamedmansour** [comment]
Thank you!

Duplicates #8
