### ISSUE TITLE
Chart Range updates incorrectly

### ISSUE THREAD

**Issue by InvisibleSymbol** [mohamedmansour/eth-burn#20]
Gets worse as more blocks get minted (y-range shrinks instead of expanding)
![](https://url.invis.cloud/uA1IPQ) ![](https://url.invis.cloud/5YlGX5)

**Comment by mohamedmansour** [comment]
Yea I think there is a bug in the `recharts` library when using `auto` for the ranges. I will create my own ranges and see if it works. Thank you!

**Comment by mohamedmansour** [comment]
I think the bug was a big number bug where sending the values as string was overflowing and treating them as exponent strings not numbers. It seems working after I Fixed #21

**Comment by mohamedmansour** [comment]
Converted it to a float after I changed it to GWEI (forgot)
![image](https://user-images.githubusercontent.com/68524/123675443-931d5880-d7f7-11eb-80af-4dba93596cd3.png)
