### ISSUE TITLE
Chart y-axis has unformatted values

### ISSUE THREAD

**Issue by InvisibleSymbol** [mohamedmansour/eth-burn#21]
Base fee shows stuff like: `100030000000`
Burned shows stuff like: `1000000000000000000` (literally only shows zeros)
I suggest to always use gwei for base fee/ ETH for burned or dynamically change the units based on what's shown
![](https://url.invis.cloud/tN8KQc)

**Comment by mohamedmansour** [comment]
Thank you! 

I can switch base fee to gwei, but for burned it will be trickier because it jumps from wei to gwei to eth easily on testnets.

**Comment by mohamedmansour** [comment]
By using ETH and GWEI that made the charts correct now and used floats vs ints: Please let me know if you see anything wrong, if you do, the value (when you hover over the dots) would help out.

![image](https://user-images.githubusercontent.com/68524/123674073-0c1bb080-d7f6-11eb-99b0-9df58813cb8b.png)

![image](https://user-images.githubusercontent.com/68524/123674093-1342be80-d7f6-11eb-98d0-974e9b2f4109.png)
