### ISSUE TITLE
Add Base Fee and Rewards API

### ISSUE THREAD

**Issue by mohamedmansour** [mohamedmansour/eth-burn#3]
Would be nice to have a base fee and rewards API so we can visualize this better.

**Comment by mohamedmansour** [comment]
@MariusVanDerWijden let me know when these API endpoints are done, I can integrate them super quick!

**Comment by MariusVanDerWijden** [comment]
So the blockreward can be calculated as
```
BlockReward = BaseReward + OmmerReward
with 
OmmerReward = (BaseReward / 8 * diff)
diff = (NoUncle + 8 - blockNr) // inclusion distance
```
`BaseReward` has been stable at 2 ETH per block so I think that can be hardcoded for the near future.
So you need to get the amount of uncles a block has via `eth.GetUncleCountByBlockNumber()` and then iterate over the uncles via `eth.GetUncleByBlockNumberAndIndex()` to retrieve the blocknumbers of the uncles to calculate the inclusion distance.

**Comment by MariusVanDerWijden** [comment]
It's actually a lot of calls so I might write an endpoint for it after all

**Comment by MariusVanDerWijden** [comment]
Alright, implemented a new endpoint `eth.getBlockReward()`which calculates the total amount of ether created by a block: https://github.com/ethereum/go-ethereum/pull/23040

**Comment by mohamedmansour** [comment]
Closing since its done, always 2ETH though, wish we can simulate it.
