### ISSUE TITLE
Error: invalid argument 0: hex number with leading zero digits

### ISSUE THREAD

**Issue by InvisibleSymbol** [mohamedmansour/eth-burn#7]
Website refuses to load because of this. I assume it has to do with Commit e7049f8ce13882c00d739f96809adc7884613338, should be pretty simple to fix?

Might as well add that it would be nice to handle errors like this (at least show a message or something). First time this happend I waited longer than I want to admit before noticing something was wrong. 

<details>
<summary> Websocket Messages: </summary>

SENT: `{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}`
RECV: `{"jsonrpc":"2.0","id":1,"result":"0x7b"}`
SENT: `{"method":"eth_blockNumber","params":[],"id":2,"jsonrpc":"2.0"}`
RECV: `{"jsonrpc":"2.0","id":2,"result":"0x10486"}`
SENT: `{"method":"eth_getBlockByNumber","params":["0x10486",false],"id":3,"jsonrpc":"2.0"}`
RECV: `{"jsonrpc":"2.0","id":3,"result":{..., number":"0x10486",...}}`
**_SENT: `{"method":"debug_getBlockReward","params":["0x010486"],"id":4,"jsonrpc":"2.0"}`_**
RECV: `{"jsonrpc":"2.0","id":4,"error":{"code":-32602,"message":"invalid argument 0: hex number with leading zero digits"}}`

</details>

**Comment by mohamedmansour** [comment]
I Am looking at it, it might be devnet no longer works. @MariusVanDerWijden  any ideas?

**Comment by mohamedmansour** [comment]
```
debug.burned('0x010486', '0x010486')
Error: invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go value of type hexutil.Uint64
        at web3.js:6357:37(47)
        at web3.js:5091:62(37)
        at <eval>:1:13(5)
```

**Comment by mohamedmansour** [comment]
From looking at https://github.com/ethereum/go-ethereum/issues/14682 it seems that error is because of the leading 0 in hex, I was always using `utils.hexlify(blockNumber)` going to find a way to remove that `0x0` prefixed I am surprised the library allows that.

**Comment by mohamedmansour** [comment]
@InvisibleSymbol thank you for this report, I deployed a new version, make sure the cache is cleaned, it seems the `ethers` library padded the hex with 0's and golang geth hex library doesn't understand padded 0's. So all the blocks in 68000 were not working. I reverted to use manual JS to convert instead.
